sudo: false
language: python
cache: pip
python:
    - "2.7"
    - "3.7"
addons:
    postgresql: "9.6"
services:
    - postgresql
branches:
    only:
        - master
        - disturbance_v3
        - apiary
        - apiary_dev
        - working-python3
        - apiary-python3

env:
    global:
        - SECRET_KEY=SecretKeyForTravis
        - DATABASE_URL="postgis://postgres@localhost:5432/travis_ci_test"
        - PRODUCTION_EMAIL=False
        - EMAIL_INSTANCE="TEST"
        - NON_PROD_EMAIL="travis@dpaw.wa.gov.au"
        - BPAY_ALLOWED=True
        - EMAIL_FROM="no-reply@dbca.wa.gov.au"
        - SUPPORT_EMAIL="test@example.com"
        - SYSTEM_NAME_SHORT="apiary"
        - SITE_DOMAIN="localhost"
        - SITE_PREFIX="das"
        - SITE_DOMAIN="dbca.wa.gov.au"
        - TENURE_SECTION="Section1-0"
sudo: true
install:
    - sudo apt-get install postgresql-9.6-postgis-2.4 libreoffice -y -q
    - pip install pip --upgrade
    - pip install -r requirements.txt
before_script:
    - touch .env
    - psql -c 'create database travis_ci_test;' -U postgres
    - python manage_ds.py migrate --noinput
script:
    - COVERAGE_FILE=.coverage_ledger coverage run --source="." manage_ds.py test --noinput ledger
    - COVERAGE_FILE=.coverage_ds coverage run --source="." manage_ds.py test --noinput disturbance/tests/
    - coverage combine .coverage_ledger .coverage_ds
after_success:
    - coveralls
